/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.Logica;
import Logica.Ruta;
import java.awt.event.ItemEvent;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class panelRuta extends javax.swing.JPanel {

    int posicion;
    JPanel panelRutas;
    Ruta ruta; 
    Logica logica;
    JPanel panelUbis;

    /**
     * Creates new form NewJPanel
     * @param panelRutas
     * @param ruta
     * @param logica
     * @param panelUbis
     */
    
    public panelRuta(Ruta ruta, Logica logica, JPanel panelUbis, JPanel panelRutas) {
        initComponents();

        this.ruta = ruta;
        this.logica = logica;
        this.panelUbis = panelUbis;
        this.panelRutas = panelRutas;
        nombreRuta.setText(ruta.getNombre());

    }

//    public panelRuta() {
//        System.out.println(ruta.getNombre());
//        initComponents();
//        
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreRuta = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(173, 70));
        setMinimumSize(new java.awt.Dimension(173, 70));
        setPreferredSize(new java.awt.Dimension(173, 70));

        nombreRuta.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        nombreRuta.setText("jCheckBox1");
        nombreRuta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nombreRutaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(nombreRuta)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nombreRuta)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreRutaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nombreRutaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {//checkbox has been selected
            logica.pintarRuta(ruta, panelUbis);
            logica.habilitaDemas(panelRutas, false);
        } else {//checkbox has been deselected
            logica.quitarRuta(ruta, panelUbis);
            logica.habilitaDemas(panelRutas, true);
        }
    }//GEN-LAST:event_nombreRutaItemStateChanged

    public JCheckBox getNombreRuta() {
        return nombreRuta;
    }

    public void setNombreRuta(JCheckBox nombreRuta) {
        this.nombreRuta = nombreRuta;
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox nombreRuta;
    // End of variables declaration//GEN-END:variables
}
