package Interfaces;


import Logica.Geocodificacion;
import Logica.Logica;
import Logica.Ubicacion;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.openstreetmap.gui.jmapviewer.interfaces.MapMarker;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alumno
 */
public class ubicacionPanel extends javax.swing.JPanel {

    private Logica logica;
    private int posicion;
    private Ubicacion ubicacion;
    private JPanel panelLista;
    private boolean elimina;
    private MapMarker mm;
     /**
     * Creates new form ubicacion
     * @param posicion
     * @param panelLista
     * @param ubicacion
     * @param logica
     */
    public ubicacionPanel(int posicion, JPanel panelLista,Ubicacion ubicacion, Logica logica,MapMarker mm ) {
        initComponents();
        this.posicion=posicion;
        this.panelLista=panelLista;
        elimina=false;
        this.ubicacion = ubicacion;
        this.logica=logica;
        this.mm=mm;
        System.out.println("El nombre es "+ubicacion.getNombre());
        nombre.setText(ubicacion.getNombre());
        numero.setText(String.valueOf(posicion));
    }

    public MapMarker getMm() {
        return mm;
    }

    public void setMm(MapMarker mm) {
        this.mm = mm;
    }

    
    public ubicacionPanel() {
        initComponents();
    }
    /**
     * @return the posicion
     */
    public int getPosicion() {
        return posicion;
    }

    /**
     * @param posicion the posicion to set
     */
    public void setPosicion(int posicion) {
        this.posicion = posicion;
    }

    /**
     * @return the ubicacionPanel
     */
    public Ubicacion getUbicacion() {
        return ubicacion;
    }

    /**
     * @param ubicacion the ubicacionPanel to set
     */
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }

    /**
     * @return the panelLista
     */
    public JPanel getPanelLista() {
        return panelLista;
    }

    /**
     * @param panelLista the panelLista to set
     */
    public void setPanelLista(JPanel panelLista) {
        this.panelLista = panelLista;
    }

    /**
     * @return the elimina
     */
    public boolean isElimina() {
        return elimina;
    }

    /**
     * @param elimina the elimina to set
     */
    public void setElimina(boolean elimina) {
        this.elimina = elimina;
    }

    public JLabel getNumero() {
        return numero;
    }

    public void setNumero(JLabel numero) {
        this.numero = numero;
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        subir = new java.awt.Button();
        bajar = new java.awt.Button();
        numero = new javax.swing.JLabel();
        subir1 = new java.awt.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(269, 65));
        setMinimumSize(new java.awt.Dimension(269, 65));
        setPreferredSize(new java.awt.Dimension(269, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        nombre.setText("ubicacion n");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, -1));

        subir.setBackground(new java.awt.Color(255, 255, 255));
        subir.setLabel("^");
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });
        add(subir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 5, -1, -1));

        bajar.setActionCommand("v");
        bajar.setBackground(new java.awt.Color(255, 255, 255));
        bajar.setLabel("v");
        bajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajarActionPerformed(evt);
            }
        });
        add(bajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, -1, -1));

        numero.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        numero.setText("n");
        add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 20, -1));

        subir1.setBackground(new java.awt.Color(255, 255, 255));
        subir1.setLabel("X");
        subir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subir1ActionPerformed(evt);
            }
        });
        add(subir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajarActionPerformed
        
        logica.moverUbicacion(panelLista,posicion,posicion+1);
        //posicion++;
        numero.setText(String.valueOf(posicion));
    }//GEN-LAST:event_bajarActionPerformed

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        logica.moverUbicacion(panelLista,posicion,posicion-1);
        //posicion--;
        numero.setText(String.valueOf(posicion));
    }//GEN-LAST:event_subirActionPerformed

    private void subir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subir1ActionPerformed
        elimina=true;
        logica.eliminarElementoPanel(panelLista);
    }//GEN-LAST:event_subir1ActionPerformed


        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bajar;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numero;
    private java.awt.Button subir;
    private java.awt.Button subir1;
    // End of variables declaration//GEN-END:variables
}
