/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iniciosesion;

import Logica.Logica;
import Logica.Usuario;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author alumno
 */
public class InicioSesion extends javax.swing.JFrame {

    Logica logica;
    /**
     * Creates new form inicioSesion
     */
    public InicioSesion() {
        initComponents();
        pwd.setTransferHandler(null);
        pwd_inicio.setTransferHandler(null);
        pwd_verifica.setTransferHandler(null);
        Image img= new ImageIcon("inicioSesion.jpg").getImage();
        ImageIcon img2=new ImageIcon(img.getScaledInstance(500, 300, Image.SCALE_SMOOTH));
        foto.setIcon(img2);
        img= new ImageIcon("registro.jpg").getImage();
        img2=new ImageIcon(img.getScaledInstance(500, 300, Image.SCALE_SMOOTH));
        fotito.setIcon(img2);
        logica=new Logica();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio_sesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pwd_inicio = new javax.swing.JPasswordField();
        usuario_inicio = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        registro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pwd_verifica = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fotito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        inicio_sesion.setBackground(new java.awt.Color(255, 255, 255));
        inicio_sesion.setMaximumSize(new java.awt.Dimension(853, 686));
        inicio_sesion.setMinimumSize(new java.awt.Dimension(853, 686));
        inicio_sesion.setPreferredSize(new java.awt.Dimension(853, 686));

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel1.setText("Nombre de usuario");

        jLabel2.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        pwd_inicio.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        usuario_inicio.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        foto.setBackground(new java.awt.Color(255, 204, 204));
        foto.setPreferredSize(new java.awt.Dimension(500, 300));

        iniciar.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        iniciar.setText("Iniciar sesión");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel9.setText("o registrate");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel10.setText("Inicio de sesión");

        jButton4.setText("M");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicio_sesionLayout = new javax.swing.GroupLayout(inicio_sesion);
        inicio_sesion.setLayout(inicio_sesionLayout);
        inicio_sesionLayout.setHorizontalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(iniciar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(250, 250, 250)
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwd_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(usuario_inicio))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel10))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        inicio_sesionLayout.setVerticalGroup(
            inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicio_sesionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(inicio_sesionLayout.createSequentialGroup()
                        .addComponent(usuario_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(inicio_sesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pwd_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciar)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(inicio_sesion, "card2");

        registro.setBackground(new java.awt.Color(255, 255, 255));
        registro.setMaximumSize(new java.awt.Dimension(853, 686));
        registro.setMinimumSize(new java.awt.Dimension(853, 686));
        registro.setPreferredSize(new java.awt.Dimension(853, 686));

        jLabel11.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel11.setText("o inicia sesión");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel4.setText("Correo electrónico");

        jLabel5.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel5.setText("Contraseña");

        email.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        pwd.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel6.setText("Repita contraseña");

        pwd_verifica.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N

        usuario.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel7.setText("Nombre de usuario");

        registrar.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        registrar.setText("Registro");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ink Free", 0, 18)); // NOI18N
        jLabel8.setText("Registro de usuario");

        jButton1.setText("M");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("M");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        fotito.setBackground(new java.awt.Color(255, 204, 204));
        fotito.setOpaque(true);
        fotito.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout registroLayout = new javax.swing.GroupLayout(registro);
        registro.setLayout(registroLayout);
        registroLayout.setHorizontalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(250, 250, 250)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(258, 258, 258)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(303, 303, 303)
                        .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(250, 250, 250)
                        .addComponent(pwd_verifica, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(fotito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(registrar))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registroLayout.setVerticalGroup(
            registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(20, 20, 20)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(registroLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(pwd_verifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(fotito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(registrar)
                .addGap(15, 15, 15)
                .addComponent(jLabel11)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(registro, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed

        //comprueba que todos los campos esten rellenos
        if(comprueba_NuevoUsuario(usuario.getText(),new String(pwd.getPassword()),new String(pwd_verifica.getPassword()),email.getText())){
            int cod=logica.compruebaUsuario(usuario.getText(), new String(pwd.getPassword()), email.getText());
            if(cod==-1){
                Usuario us=new Usuario(-1,usuario.getText(), new String(pwd.getPassword()), email.getText());
                logica.crear_usuario(us);
                CardLayout name = (CardLayout) getContentPane().getLayout();
                name.next(getContentPane());
            }
            else{
                JOptionPane.showMessageDialog(null, "ya existe un usuario con ese nombre o con ese correo");
            }
            
        }
        
    }//GEN-LAST:event_registrarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        if(logica.compruebaUsuario(usuario_inicio.getText(), new String(pwd_inicio.getPassword()))){
            
            JOptionPane.showMessageDialog(null, "Has podido entrar");
            setVisible(false);
            Principal sesion = new Principal();
            sesion.setVisible( true );
            sesion.setLogica(logica);
            //inicar app
        } else{
            JOptionPane.showMessageDialog(null, "No has podido entrar");
        }
    }//GEN-LAST:event_iniciarActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        CardLayout name = (CardLayout) getContentPane().getLayout();
        name.next(getContentPane());
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(pwd.getEchoChar()=='*'){
            pwd.setEchoChar((char)0);
        }else{
            pwd.setEchoChar('*');
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(pwd_verifica.getEchoChar()=='*'){
            pwd_verifica.setEchoChar((char)0);
        }else{
            pwd_verifica.setEchoChar('*');
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(pwd_inicio.getEchoChar()=='*'){
            pwd_inicio.setEchoChar((char)0);
        }else{
            pwd_inicio.setEchoChar('*');
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        CardLayout name = (CardLayout) getContentPane().getLayout();
        name.next(getContentPane());
    }//GEN-LAST:event_jLabel11MouseClicked

    //funcion que todos los com campos para el registro estén rellenos
    private boolean comprueba_NuevoUsuario(String usuario,String contraseña,String contraseñaverifica,String email){
        boolean flag=true;
        //si este campo de texto esta vacio
        if(usuario.isBlank()||usuario.isEmpty()){
            flag=false;
            JOptionPane.showMessageDialog(null, "usuario vacio");
        }
        if(contraseña.equals(contraseñaverifica)){
            if((contraseña.length()<6)||(!contraseña.contains("."))){
                flag=false;
                JOptionPane.showMessageDialog(null, "contraseña no valida");
            }
        }
        else{
            flag=false;
            JOptionPane.showMessageDialog(null, "las dos contraseñas no son iguales");
        }
        if((!email.contains("@"))||(!email.contains(".com"))){
            flag=false;
            JOptionPane.showMessageDialog(null, "email no valido");
        }
        return flag;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel fotito;
    private javax.swing.JLabel foto;
    private javax.swing.JButton iniciar;
    private javax.swing.JPanel inicio_sesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JPasswordField pwd_inicio;
    private javax.swing.JPasswordField pwd_verifica;
    private javax.swing.JButton registrar;
    private javax.swing.JPanel registro;
    private javax.swing.JTextField usuario;
    private javax.swing.JTextField usuario_inicio;
    // End of variables declaration//GEN-END:variables
}
